<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aceitar Todos</name>
   <tag></tag>
   <elementGuidId>d446a13d-030b-4e5d-b001-25d2597ef795</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0cdf5d62-2dce-4d63-99f0-93a9230b2074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll</value>
      <webElementGuid>1301e6fd-8431-4e75-8625-566d6dac153f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyButton</value>
      <webElementGuid>55838083-1296-4ae2-a139-081e466945c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>47dbbfef-8b69-4b51-a180-7c9052655f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>pt</value>
      <webElementGuid>d1bac906-db90-4e16-9d4e-4e55f8354478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceitar Todos</value>
      <webElementGuid>e0b1db1b-ef20-461b-bd39-1258e0d23e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll&quot;)</value>
      <webElementGuid>fef0e68e-48f0-4c70-8a2e-cdf7fbb2e987</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll']</value>
      <webElementGuid>d997e69b-048d-4d37-90f5-c51d5335dcef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyButtonsWrapper']/button[4]</value>
      <webElementGuid>ef9a85ec-5a26-4343-90ec-df2f778e5ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalizar'])[1]/following::button[1]</value>
      <webElementGuid>e0cf366c-bd4d-4f9b-9107-74421d5f1513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar'])[1]/following::button[2]</value>
      <webElementGuid>cadedbdb-afa8-4ec4-842d-3ae37d738306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookiebot by Usercentrics'])[1]/preceding::button[1]</value>
      <webElementGuid>3c7b4aa8-5ea5-4ee2-a82e-4f7b49ee8449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceitar Todos']/parent::*</value>
      <webElementGuid>3fa19900-8af4-4911-93b2-0dd9f4867cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>5c950d03-95de-4043-9bac-aaf3a2150555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll' and (text() = 'Aceitar Todos' or . = 'Aceitar Todos')]</value>
      <webElementGuid>0c492f1f-170d-49b5-b68f-e680d059c95d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
