<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Carrinho</name>
   <tag></tag>
   <elementGuidId>9584407c-a2ee-4288-a0a8-c96adddea174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.add-to-cart.js-add-to-cart.js-add-to-cart-button.button.col-button.button--primary.col-button--primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontent']/div/div/div[2]/div[2]/div/div[3]/div[4]/div[3]/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>956a724a-b96b-40eb-9408-ba068ae0f91e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>add-to-cart js-add-to-cart js-add-to-cart-button button col-button button--primary col-button--primary</value>
      <webElementGuid>a80695d5-6f40-4c95-b09d-cf1c75240ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>26f2711a-799b-4c20-819c-5820efe7e2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#chooseBonusProductModal</value>
      <webElementGuid>93da3749-928b-417a-a9df-6e1c94665d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pid</name>
      <type>Main</type>
      <value>6113720</value>
      <webElementGuid>32b37ac5-28ba-499a-b943-cb6cc1ed5039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-outofstock</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b1083c6-941a-4824-ac41-bc158e5663e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>pdp</value>
      <webElementGuid>fd7d8379-f338-4400-b6fe-6d97c2cef62b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-availablevariations</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>5dc85a03-afd4-4d90-96ee-c075be62fcac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cart-quickview-txt</name>
      <type>Main</type>
      <value>Atualizar</value>
      <webElementGuid>95c4a976-f027-46a3-b1b3-db6b1fa15fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-update-variant-url</name>
      <type>Main</type>
      <value>/on/demandware.store/Sites-continente-Site/default/Cart-EditProductLineItem</value>
      <webElementGuid>5b1245c7-10e7-4793-a73f-5c7937ba0965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Carrinho
</value>
      <webElementGuid>72dca248-cf52-4190-8c32-76aff155d99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;row no-gutters product-detail product-wrapper&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row no-gutters product-images-container&quot;]/div[@class=&quot;col-12 col-sm-7 col-md-6 product-name-details&quot;]/div[@class=&quot;product-name-details--wrapper pwc-border--radius&quot;]/div[@class=&quot;attributes&quot;]/div[@class=&quot;row no-gutters prices-add-to-cart-actions&quot;]/div[@class=&quot;row no-gutters col-12 col-md-4 col-sm-9 ct-pdp--favorite-addCTA&quot;]/div[@class=&quot;col col-md-auto ct-pdp--add-CTA cart-and-ipay has-measurement&quot;]/button[@class=&quot;add-to-cart js-add-to-cart js-add-to-cart-button button col-button button--primary col-button--primary&quot;]</value>
      <webElementGuid>9744af6f-2da7-4df5-b4ad-adb9b78c894c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div/div[2]/div[2]/div/div[3]/div[4]/div[3]/div[2]/button</value>
      <webElementGuid>f8dc8d03-745e-47ee-af04-3dc0017eb716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantidade no carrinho'])[1]/following::button[3]</value>
      <webElementGuid>933732fa-c067-4738-bf31-d50f1fdf4b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/lt'])[1]/following::button[5]</value>
      <webElementGuid>7ac709a2-cdc7-42b5-a5f0-f9262c4d0fa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicione Comentários'])[1]/preceding::button[2]</value>
      <webElementGuid>797e969e-581b-4fcd-a06b-eb88e3447131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caraterísticas'])[1]/preceding::button[5]</value>
      <webElementGuid>987b70bc-35d8-476e-8f64-ec830a2f6cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Carrinho']/parent::*</value>
      <webElementGuid>9a36da07-a7e4-4c13-a96a-2fb99034951e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/button</value>
      <webElementGuid>faaa79b4-aa9f-4ad0-a303-f7acdd68fc7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
Carrinho
' or . = '
Carrinho
')]</value>
      <webElementGuid>bd5402e7-f1aa-4f3c-a192-e798f2cdf9a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
