<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Quantidade no carrinho_increase-quan_d2e8f5</name>
   <tag></tag>
   <elementGuidId>fcca593e-5d5b-4a36-9dba-9fbce18e3ce8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.increase-quantity-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='maincontent']/div/div/div[2]/div[2]/div/div[3]/div[4]/div[3]/div[2]/div/div[2]/div/span[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0922b752-62ba-4cac-8db3-2646c984a5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>baa80b55-956f-451d-932a-e93bf4004cf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Aumentar quantidade</value>
      <webElementGuid>0dcd8187-1707-4bd6-b605-d892641b5e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>increase-quantity-btn</value>
      <webElementGuid>56918b0d-9a76-4c50-a5f9-5648aaa21e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;row no-gutters product-detail product-wrapper&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;row no-gutters product-images-container&quot;]/div[@class=&quot;col-12 col-sm-7 col-md-6 product-name-details&quot;]/div[@class=&quot;product-name-details--wrapper pwc-border--radius&quot;]/div[@class=&quot;attributes&quot;]/div[@class=&quot;row no-gutters prices-add-to-cart-actions&quot;]/div[@class=&quot;row no-gutters col-12 col-md-4 col-sm-9 ct-pdp--favorite-addCTA&quot;]/div[@class=&quot;col col-md-auto ct-pdp--add-CTA cart-and-ipay has-measurement&quot;]/div[@class=&quot;ct-tile-quantity pdp-qty-tile&quot;]/div[@class=&quot;ct-tile-quantity-update quantity-update product-qty-vue&quot;]/div[@class=&quot;quantity-input-wrapper col-quantity-input-wrapper has-units&quot;]/span[@class=&quot;quantity-icon quantity-icon--plus&quot;]/button[@class=&quot;increase-quantity-btn&quot;]</value>
      <webElementGuid>5f938018-3236-4655-ac25-d1ac0e3306a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div/div/div[2]/div[2]/div/div[3]/div[4]/div[3]/div[2]/div/div[2]/div/span[2]/button</value>
      <webElementGuid>6e8291fd-6d0e-4ae8-a0b1-345c0e9ee978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quantidade no carrinho'])[1]/following::button[2]</value>
      <webElementGuid>ac516fe5-154b-4c6c-b30a-58a7582b45a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/lt'])[1]/following::button[4]</value>
      <webElementGuid>0fea38f6-4f39-41d1-a8b5-888c4c01e189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Carrinho'])[1]/preceding::button[1]</value>
      <webElementGuid>3978d8a7-1b38-4148-82f4-400583427b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adicione Comentários'])[1]/preceding::button[3]</value>
      <webElementGuid>d72f4d75-7f7c-4d1b-83cf-50c8e981acf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/button</value>
      <webElementGuid>8fe3e012-8a6f-4682-9803-71d173017b6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
