<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Carrinho_ct-tile-image lazyloaded</name>
   <tag></tag>
   <elementGuidId>2d008687-a5e8-4b12-a5da-bf9c6aa2d09d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.product-tile.pid-6437987.ct-product-tile.col-product-tile.data-layer-pushed > div.ct-inner-tile-wrap.col-inner-tile-wrap.row.no-gutters.justify-content-center.align-content-start > div.ct-image-container.col-4.col-sm > a > picture.intrinsic.intrinsic--square.intrinsic--square > img.ct-tile-image.lazyloaded</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id=''])[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>17b54273-cac0-45a5-a282-1c72cabd2d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-tile-image lazyloaded</value>
      <webElementGuid>587c5885-a83c-493c-a450-3e402a37cf53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>65338f08-d0ee-4eb9-a57c-42414b4a215c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-continente-Site/-/default/dw132e3de0/images/noimagelarge_product.png';</value>
      <webElementGuid>c34520bb-006b-4dca-85d4-a000607c73e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw23eb408c/images/col/643/6437987-direito.jpg?sw=280&amp;sh=280</value>
      <webElementGuid>db475150-619c-4e74-8d47-dacc713d3ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bebida Vegetal de Arroz</value>
      <webElementGuid>8d25cd71-3884-4dae-92c7-0c0a388dc3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bebida Vegetal de Arroz</value>
      <webElementGuid>634cd166-01c1-4303-99d9-b0f1b69e76fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw23eb408c/images/col/643/6437987-direito.jpg?sw=280&amp;sh=280</value>
      <webElementGuid>69a66673-859e-4a3d-9b42-bf6c70644c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;container-margin search-results&quot;]/div[@class=&quot;search-results-grid&quot;]/div[@class=&quot;results-section&quot;]/div[@class=&quot;row product-grid no-gutters gtm-list&quot;]/div[@class=&quot;col-12 col-sm-3 col-lg-2 productTile&quot;]/div[@class=&quot;product&quot;]/div[@class=&quot;product-tile pid-6437987 ct-product-tile col-product-tile data-layer-pushed&quot;]/div[@class=&quot;ct-inner-tile-wrap col-inner-tile-wrap row no-gutters justify-content-center align-content-start&quot;]/div[@class=&quot;ct-image-container col-4 col-sm&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square intrinsic--square&quot;]/img[@class=&quot;ct-tile-image lazyloaded&quot;]</value>
      <webElementGuid>18a223a0-36ea-4632-86ca-bd1bb4fa1b00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id=''])[7]</value>
      <webElementGuid>f07dc7d3-608f-40fe-9530-2bb625d204c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='maincontent']/div[2]/div[4]/div[2]/div[4]/div[7]/div/div/div/div/a/picture/img</value>
      <webElementGuid>768adfb1-bdaf-4b46-a793-6cf99d98bdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Bebida Vegetal de Arroz'])[2]</value>
      <webElementGuid>da3f9010-0365-4370-b59f-dda68ee5d085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div/a/picture/img</value>
      <webElementGuid>99029c74-cdca-454e-a1dc-337b64ea439c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Bebida Vegetal de Arroz' and @title = 'Bebida Vegetal de Arroz' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw23eb408c/images/col/643/6437987-direito.jpg?sw=280&amp;sh=280']</value>
      <webElementGuid>4991ac38-4770-4e0a-9ff6-1ec0a0814ff4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
