<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Continente Bio_img-fluid pwc-border--radius</name>
   <tag></tag>
   <elementGuidId>76919c11-7b96-44e1-ada2-bbe6b97e7c70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide00']/div/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.pwc-border--radius</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a5dd59f-47dd-49ff-9bd3-c3dba9fae52f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid pwc-border--radius</value>
      <webElementGuid>e6f4964e-e6a4-46cd-b11d-b38826f70b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-global-navigation-catalog/default/dwf48c4c6e/images/marcas/marca-propria/standard/bio-bebidas-vegetais.jpg?sw=600&amp;sh=150</value>
      <webElementGuid>0a0695ab-2a2c-4bf2-a563-57df44eba475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bebidas Vegetais</value>
      <webElementGuid>b8becc49-e217-40d3-8a5a-1a4ff4a9aff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bebidas Vegetais</value>
      <webElementGuid>e788760f-b17b-49c4-a600-d9d3f0b07a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide00&quot;)/div[@class=&quot;category-tile-image pwc-border--radius&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--category-tile&quot;]/img[@class=&quot;img-fluid pwc-border--radius&quot;]</value>
      <webElementGuid>05070399-0d4a-403d-99d1-b95344e26209</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide00']/div/a/picture/img</value>
      <webElementGuid>e52aa52c-4d43-450a-99bd-66c932d45a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Bebidas Vegetais']</value>
      <webElementGuid>305f7200-a802-4c03-8fa5-3c72a3fc8d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/picture/img</value>
      <webElementGuid>bf1860d0-8a21-4068-85b1-82733ae656d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-global-navigation-catalog/default/dwf48c4c6e/images/marcas/marca-propria/standard/bio-bebidas-vegetais.jpg?sw=600&amp;sh=150' and @alt = 'Bebidas Vegetais' and @title = 'Bebidas Vegetais']</value>
      <webElementGuid>5b87ab2e-cccb-4248-a880-6a701d18180e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
