<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Subscrever</name>
   <tag></tag>
   <elementGuidId>e42b6ad1-c10b-4257-8077-ab5018081a8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.button.col-button.button--secondary.col-button--secondary.pwc-mb--20.newsletter-button.subscribe-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>18647cd5-fa48-4cf9-90ac-206f972bfd58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>1db5f27d-2c7f-42bf-aa71-2671f2130600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button col-button button--secondary col-button--secondary pwc-mb--20 newsletter-button subscribe-email</value>
      <webElementGuid>857e0e66-5105-482d-b62a-e3e94e2b6140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>https://www.continente.pt/on/demandware.store/Sites-continente-Site/default/EmailSubscribe-Subscribe</value>
      <webElementGuid>4e8562fd-75be-4d07-8a8e-1e2c2a2834bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscrever </value>
      <webElementGuid>dd25fada-2e83-4d77-8323-ef0ebe0e16a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footercontent&quot;)/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;pwc-container&quot;]/div[@class=&quot;pwc-container--px-70&quot;]/div[@class=&quot;newsletter-email-signup&quot;]/form[1]/div[@class=&quot;newsletter-wrapper col-newsletter-wrapper&quot;]/div[@class=&quot;newsletter-button-wrap col-newsletter-button-wrap&quot;]/div[@class=&quot;input-group-append&quot;]/button[@class=&quot;button col-button button--secondary col-button--secondary pwc-mb--20 newsletter-button subscribe-email&quot;]</value>
      <webElementGuid>56c6cc0e-96d4-4a9f-b825-9f97dd7a43a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[3]</value>
      <webElementGuid>35f589e9-505a-415c-a8ae-914456594239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//footer[@id='footercontent']/div/div/div/div/form/div/div[4]/div/button</value>
      <webElementGuid>ee494119-fe63-4821-bab4-52849890ed4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='marketing'])[1]/following::button[1]</value>
      <webElementGuid>0a798c17-5bce-46e3-932b-53ac72566725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modelo Continente Hipermercados, S.A. (MCH)'])[1]/following::button[1]</value>
      <webElementGuid>1f053c37-25a1-4e28-adae-1ff8a96045a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Métodos de pagamento aceites'])[1]/preceding::button[1]</value>
      <webElementGuid>ad6d7b2d-162f-4849-ab41-c66b0b327688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contactos'])[1]/preceding::button[1]</value>
      <webElementGuid>5c70bf84-7a09-48ff-9088-c1622617a587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subscrever']/parent::*</value>
      <webElementGuid>9e914af4-aec3-49b3-ac92-46ad443ae3bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[4]/div/button</value>
      <webElementGuid>2810b25f-0975-4699-8417-bbf68002f558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Subscrever ' or . = 'Subscrever ')]</value>
      <webElementGuid>390fcf21-6c22-4f64-bcd1-5bf625392cff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
