<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Permitir todos</name>
   <tag></tag>
   <elementGuidId>e808aab0-15cc-4889-b20a-4e5fd8e58f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d6adf9e9-611f-4c15-bf44-0a06c4eb8803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll</value>
      <webElementGuid>d30ea509-24e3-47d3-83bc-f17045d6daa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CybotCookiebotDialogBodyButton</value>
      <webElementGuid>f13f3c52-ede0-4c32-aa75-cad9465161e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0dbf75e2-e9ea-419b-b38b-e7b31178ecce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lang</name>
      <type>Main</type>
      <value>pt</value>
      <webElementGuid>6d03634c-72d7-4a5e-b9e4-8b1ae44521b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Permitir todos</value>
      <webElementGuid>b767db5d-bd00-46a9-a507-48f105ddd536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll&quot;)</value>
      <webElementGuid>bc26adae-5100-4881-8ba6-88b29cf0c089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll']</value>
      <webElementGuid>d46c447c-ce92-422c-8ccd-2c398b2babc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CybotCookiebotDialogBodyButtonsWrapper']/button[4]</value>
      <webElementGuid>90aca64f-55e5-438a-83e6-7081e5219c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personalizar'])[1]/following::button[1]</value>
      <webElementGuid>75c6083c-c3d8-46ed-8936-0fde03cfb24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirmar'])[1]/following::button[2]</value>
      <webElementGuid>79efa4ab-6386-4b8f-a5a3-c7d7c9d88f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cookiebot by Usercentrics'])[1]/preceding::button[1]</value>
      <webElementGuid>68136be1-5b63-4b03-88fa-606ce781e9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Permitir todos']/parent::*</value>
      <webElementGuid>3a47d9ff-4829-4078-8027-5e17675a8029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>6a24c047-bdb4-40d9-a32d-2043c4c22916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll' and (text() = 'Permitir todos' or . = 'Permitir todos')]</value>
      <webElementGuid>fa65c4cc-3fc1-4b83-b58a-fe25f0523806</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
