<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Continente Equilbrio_lazyloaded</name>
   <tag></tag>
   <elementGuidId>187fee6b-1ec1-4e68-a95e-f3e8f932748d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='col-homepage']/div/div/div/div/div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0641f314-8c60-4584-814b-54666b2a86f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>ac94e794-a124-4b22-8a92-c980a00cf9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>da8fb8bf-8165-4f8d-8292-6c741ffcecd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>aed13ce2-364e-42d0-91cc-a08b63ca9f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marca Continente Bio</value>
      <webElementGuid>3521a30a-8362-4bbe-b039-76e09efb0b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marca Continente Bio</value>
      <webElementGuid>b126d111-9477-4a04-aa20-7446e7278f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>d1b4624b-62a3-43fe-ac9c-83b5dba9830e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-homepage&quot;)/div[@class=&quot;fullpage&quot;]/div[@class=&quot;no-padding--sides&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;experience-component experience-commerce_layouts-popularCategories&quot;]/div[@class=&quot;popular-categories&quot;]/div[@class=&quot;row mx-0 category-layout-grid&quot;]/div[@class=&quot;col-sm-2 col-4 category-tile-wrapper&quot;]/div[@class=&quot;image-cropper&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>5600be53-51f2-4fb8-a301-ce7524545be6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='col-homepage']/div/div/div/div/div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      <webElementGuid>cd2c2f6b-7203-4fc9-846f-f37c072cf3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Marca Continente Bio']</value>
      <webElementGuid>20ed634c-b3e8-4d0f-a024-a207a5eb3a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      <webElementGuid>0854ce4b-cde0-4594-b9ae-8dc796c3cf2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Marca Continente Bio' and @title = 'Marca Continente Bio' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit']</value>
      <webElementGuid>7732bfe1-815a-4aeb-9395-814fa9785d65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
