<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Carrinho_ct-tile-image lazyloaded</name>
   <tag></tag>
   <elementGuidId>92c3d2c8-071f-46ab-8a16-273e1a7504df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//img[@id=''])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b77b1af0-180c-42a4-b988-af0df2226f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ct-tile-image lazyloaded</value>
      <webElementGuid>181ec292-da5c-4f15-a929-3b7104c065f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>9a33a6a7-366f-4887-a338-931f9ea04b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='/on/demandware.static/Sites-continente-Site/-/default/dw132e3de0/images/noimagelarge_product.png';</value>
      <webElementGuid>9d50538d-d28e-4457-96ae-7669b4e7c314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw75e36e3c/images/col/611/6113720-hero.jpg?sw=280&amp;sh=280</value>
      <webElementGuid>365aa63e-f3f8-4cf5-886c-5f011e880cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Cerveja com Álcool</value>
      <webElementGuid>ae77558c-ad38-4f8c-88ed-4c555e5da136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cerveja com Álcool</value>
      <webElementGuid>17e47da8-6183-4858-98be-cf6600a90a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw75e36e3c/images/col/611/6113720-hero.jpg?sw=280&amp;sh=280</value>
      <webElementGuid>9f282841-6ad2-486b-a4e6-aa08836b0194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide30&quot;)/div[@class=&quot;product&quot;]/div[@class=&quot;product-tile pid-6113720   ct-product-tile col-product-tile&quot;]/div[@class=&quot;ct-inner-tile-wrap col-inner-tile-wrap row no-gutters justify-content-center align-content-start&quot;]/div[@class=&quot;ct-image-container col-4 col-sm&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square intrinsic--square&quot;]/img[@class=&quot;ct-tile-image lazyloaded&quot;]</value>
      <webElementGuid>39907ee8-4b3e-44fe-93cb-c309a9369995</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//img[@id=''])[5]</value>
      <webElementGuid>69e0cc07-3eac-4a0e-996f-ad8e0c5f32e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide30']/div/div/div/div[2]/a/picture/img</value>
      <webElementGuid>136fe0aa-b531-4cc0-9592-ea477d376cb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Cerveja com Álcool']</value>
      <webElementGuid>5ba9999f-67ee-4fb8-b223-04aacfaba6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/a/picture/img</value>
      <webElementGuid>c7bd54e0-31d1-4618-bd2d-b7b3d1e705e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Cerveja com Álcool' and @title = 'Cerveja com Álcool' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-col-master-catalog/default/dw75e36e3c/images/col/611/6113720-hero.jpg?sw=280&amp;sh=280']</value>
      <webElementGuid>096bd60a-8b87-4f91-a167-2c77b5099d4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
