<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Continente Equilbrio_lazyloaded</name>
   <tag></tag>
   <elementGuidId>187fee6b-1ec1-4e68-a95e-f3e8f932748d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='col-homepage']/div/div/div/div/div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>60087e61-69a1-4270-9972-6f63fe7c5a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazyloaded</value>
      <webElementGuid>8791b6c8-28e3-407d-b12c-f57fadac195a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8160a4c9-a65a-4a42-a63d-48cc6cada28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>b016be0c-f25b-442d-9990-3b10c90f83d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marca Continente Bio</value>
      <webElementGuid>65ff614b-1d6d-4c46-91ff-596ca6a97f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marca Continente Bio</value>
      <webElementGuid>16927a3c-19bf-46a7-9a41-1e717554ebae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit</value>
      <webElementGuid>fed9ddef-2912-40d8-9588-18f8f25776d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;col-homepage&quot;)/div[@class=&quot;fullpage&quot;]/div[@class=&quot;no-padding--sides&quot;]/div[@class=&quot;row no-gutters&quot;]/div[@class=&quot;col-12&quot;]/div[@class=&quot;experience-component experience-commerce_layouts-popularCategories&quot;]/div[@class=&quot;popular-categories&quot;]/div[@class=&quot;row mx-0 category-layout-grid&quot;]/div[@class=&quot;col-sm-2 col-4 category-tile-wrapper&quot;]/div[@class=&quot;image-cropper&quot;]/a[1]/picture[@class=&quot;intrinsic intrinsic--square&quot;]/img[@class=&quot;lazyloaded&quot;]</value>
      <webElementGuid>1efb5b23-13cb-4030-85ee-57cd1262c0a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='col-homepage']/div/div/div/div/div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      <webElementGuid>bef0dd7b-6b48-44eb-9f31-ccb763d66e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Marca Continente Bio']</value>
      <webElementGuid>455db112-797f-468f-bcc4-4c5a3db56998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]/div[3]/div/a/picture/img</value>
      <webElementGuid>ec2d74b9-a70c-4a70-9f59-b772d9fa5e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Marca Continente Bio' and @title = 'Marca Continente Bio' and @src = 'https://www.continente.pt/dw/image/v2/BDVS_PRD/on/demandware.static/-/Sites-continente-Library/default/dwd4b2b3ad/images/pages/marca-propria/continente-bio-bola-home.jpg?sw=270&amp;sh=270&amp;sm=fit']</value>
      <webElementGuid>a79411ee-a1e4-486c-a0c6-6ddd342b1697</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
